FROM nginx:alpine
COPY . /usr/share/nginx/html

# Descargamos de internet un servidor web "Nginx" la versión "Alpine" (SO Linux)
# COPY . /usr/share/nginx/html. Aca agarramos todos los archivos de la carpeta raiz (de Frontend) y los pegamos en la carpeta /usr/share/nginx/html dentro del contenedor
# En esa ruta puntualmente porque es la carpeta por defecto donde Nginx busca las pag web

