version: '3.9'

services:
  broker:
    image: eclipse-mosquitto:2
    container_name: mosquitto_real
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    #aca establecemos que el archivo mosquitto.conf q esta en la raiz de Entorno_real sobrescriba al archivo mosquitto.conf del contenedor q esta en la ruta mosquitto/config/mosquitto.conf (el broker al inciar busca en esa ruta dicho archivo para iniciar con la configuracion indicada en él)

    restart: unless-stopped
    #con esta instruccion le decimos al contenedor que si falla o se detiene, se vuelva a iniciar automaticamente

  frontend:
    build: ./Frontend
    container_name: frontend_real
    ports:
      - "8080:80"
    depends_on:
      - broker
    restart: unless-stopped

# Mapeamos el puerto 80 del contenedor al 8080 de la PC para acceder al frontend desde el navegador (ya q el navegador de nuestra PC no forma parte de la red de contenedores)
