#Archivo de configuración del broker MQTT (sobreescribimos las config iniciales que trae la img de mosquitto que descargamos en el contenedor)

persistence true
persistence_location /mosquitto/data/ # Guarda los mensajes en caso de que el broker se reinicie
log_dest file /mosquitto/log/mosquitto.log # Guarda los logs del broker

listener 1883 # Permite conexiones externas (no solo localhost)
allow_anonymous true # Permite conexiones sin usuario y contraseña
