#Archivo de configuración del broker MQTT (sobreescribimos las config iniciales que trae la img de mosquitto que descargamos en el contenedor)

persistence true
persistence_location /mosquitto/data/ # Guarda los mensajes en caso de que el broker se reinicie
log_dest stdout
log_type all

listener 1883 # Permite conexiones externas (no solo localhost sino q de otros contenedores o pcs dentro de la misma red, en este caso de la red que creamos con el docker-compose)
allow_anonymous true # Permite conexiones al broker sin usuario y contraseña (esta config se pone para cada puerto)

listener 9001 # Escucha en el puerto 9001
protocol websockets # Permite conexiones a traves de protocolo websockets
allow_anonymous true # Permite conexiones al broker sin usuario y contraseña (est se configura para cada puerto)

# Para acceder al broker DESDE APPS DE ESCRITORIO usas el puerto 1883 de la PC q esta mapeado al 1883 del contenedor (el q tiene al broker y esta dentro de la red de contenedores)
# Para acceder al broker DESDE NAVEGADORES usas el 9001 de la PC q esta mapeado al 9001 del container q tiene al broker. Esto pq los navegadores no hablan MQTT puro (deben encapsular los datos en el protocolo de red WebSockets)

# Dado q la PC no forma parte de la red de contenedores se debe hacer el mapeo de puertos, dicho mapeo permite ingresar a los servicios del compose desde la PC usando su direccion + puerto
