#Archivo de configuración del broker MQTT (sobreescribimos las config iniciales que trae la img de mosquitto que descargamos en el contenedor)

persistence true
persistence_location /mosquitto/data/ # Guarda los mensajes en caso de que el broker se reinicie
log_dest file /mosquitto/log/mosquitto.log # Guarda los logs del broker

listener 1883 # Permite conexiones externas (no solo localhost sino q de otros contenedores dentro de la misma red que tenemos en Docker)
allow_anonymous true # Permite conexiones sin usuario y contraseña

listener 9001 # Escucha en el puerto 9001 para conexiones externas de navegadores web
protocol websockets # Permite conexiones a traves de websockets
allow_anonymous true # Permite conexiones sin usuario y contraseña

#En el docker-compose mapeamos el puerto 9001 del contenedor al puerto 9001 de la PC para que la PC ingrese a la red q crea el compose y pueda acceder al broker (tambien mapeamos el 1883)

# Para acceder al broker DESDE APPS DE ESCRITORIO usas el puerto 1883 de la PC q esta mapeado al 1883 del contenedor (el q tiene al broker y esta dentro de la red de contenedores)
# Para acceder al broker DESDE NAVEGADORES usas el 9001 de la PC q esta mapeado al 9001 del container q tiene al broker. Esto pq los navegadores no hablan MQTT puro (deben encapsular los datos en el protocolo de red "WebSockets")

# Dado q la PC no forma parte de la red de contenedores se debe hacer el mapeo de puertos, dicho mapeo permite ingresar a los servicios del compose desde la PC usando su direccion + puerto
